# Options for analysis running. See https://golangci-lint.run/usage/configuration/ for config options.
run:
  timeout: 5m
issues:
  max-issues-per-linter: 0 # infinite
  max-same-issues: 0 # infinite
  fix: true
  exclude:
  # see https://github.com/stretchr/testify/issues/1199#issuecomment-1215592618, testify shows vet problem
    - 'github.com\/stretchr\/testify\/suite\.Suite contains sync\.RWMutex'
linters:
  enable:
    - gofumpt
    - gci
    - whitespace
    - misspell
    - goimports
linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft) # comet
      - prefix(github.com/cosmos) # cosmos org
      - prefix(cosmossdk.io) # new modules
      - prefix(github.com/cosmos/cosmos-sdk) # old sdk import
      - prefix(github.com/archway-network/archway)
    custom-order: true
  misspell:
    locale: US
