before:
  hooks:
    - wget https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.a
    - apt install musl-dev
builds:
  - id: linux-amd64
    main: ./cmd/archwayd
    binary: archwayd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=archway -X github.com/cosmos/cosmos-sdk/version.AppName=archway -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - muslc
