coverage:
  status:
    project:
      default:
        target: 70
        threshold: 1%

    patch:
      default: false
ignore:
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "third_party"
  - "vendor"
  - "pkg/"

