// DONTCOVER
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archway/rewards/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the initial state of the tracking module.
type GenesisState struct {
	// params defines all the module parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// contracts_metadata defines a list of all contracts metadata.
	ContractsMetadata []ContractMetadata `protobuf:"bytes,2,rep,name=contracts_metadata,json=contractsMetadata,proto3" json:"contracts_metadata"`
	// block_rewards defines a list of all block rewards objects.
	BlockRewards []BlockRewards `protobuf:"bytes,3,rep,name=block_rewards,json=blockRewards,proto3" json:"block_rewards"`
	// tx_rewards defines a list of all tx rewards objects.
	TxRewards []TxRewards `protobuf:"bytes,4,rep,name=tx_rewards,json=txRewards,proto3" json:"tx_rewards"`
	// min_consensus_fee defines the minimum gas unit price.
	MinConsensusFee types.DecCoin `protobuf:"bytes,5,opt,name=min_consensus_fee,json=minConsensusFee,proto3" json:"min_consensus_fee"`
	// rewards_records defines a list of all active (undistributed) rewards records.
	RewardsRecords []RewardsRecord `protobuf:"bytes,6,rep,name=rewards_records,json=rewardsRecords,proto3" json:"rewards_records"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdced50517b403fe, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetContractsMetadata() []ContractMetadata {
	if m != nil {
		return m.ContractsMetadata
	}
	return nil
}

func (m *GenesisState) GetBlockRewards() []BlockRewards {
	if m != nil {
		return m.BlockRewards
	}
	return nil
}

func (m *GenesisState) GetTxRewards() []TxRewards {
	if m != nil {
		return m.TxRewards
	}
	return nil
}

func (m *GenesisState) GetMinConsensusFee() types.DecCoin {
	if m != nil {
		return m.MinConsensusFee
	}
	return types.DecCoin{}
}

func (m *GenesisState) GetRewardsRecords() []RewardsRecord {
	if m != nil {
		return m.RewardsRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "archway.rewards.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("archway/rewards/v1beta1/genesis.proto", fileDescriptor_cdced50517b403fe)
}

var fileDescriptor_cdced50517b403fe = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0xcf, 0xd2, 0x30,
	0x18, 0xc7, 0x37, 0x41, 0x12, 0x0b, 0x4a, 0x68, 0x4c, 0x5c, 0x88, 0x19, 0x84, 0x04, 0x83, 0x07,
	0xbb, 0x80, 0x67, 0x2f, 0x60, 0xe4, 0xa2, 0x86, 0xa0, 0x5e, 0x3c, 0xb8, 0x74, 0xe5, 0x71, 0x2c,
	0xb8, 0x96, 0xb4, 0x45, 0xe0, 0x5b, 0xf8, 0xb1, 0x38, 0x72, 0xf4, 0x64, 0x0c, 0x7c, 0x80, 0xf7,
	0x2b, 0xbc, 0x59, 0xd7, 0x2d, 0xbc, 0x87, 0xdd, 0xb6, 0xa7, 0xbf, 0xe7, 0xf7, 0xfc, 0xd3, 0x3e,
	0x68, 0x48, 0x25, 0x5b, 0xef, 0xe9, 0x31, 0x90, 0xb0, 0xa7, 0x72, 0xa5, 0x82, 0xdf, 0xe3, 0x08,
	0x34, 0x1d, 0x07, 0x31, 0x70, 0x50, 0x89, 0x22, 0x5b, 0x29, 0xb4, 0xc0, 0x2f, 0x2c, 0x46, 0x2c,
	0x46, 0x2c, 0xd6, 0x7d, 0x1e, 0x8b, 0x58, 0x18, 0x26, 0xc8, 0xbe, 0x72, 0xbc, 0xeb, 0x33, 0xa1,
	0x52, 0xa1, 0x82, 0x88, 0x2a, 0x28, 0x8d, 0x4c, 0x24, 0xdc, 0x9e, 0x57, 0x4e, 0x2d, 0xf4, 0x06,
	0x1b, 0xdc, 0xd5, 0x50, 0x6b, 0x9e, 0xe7, 0xf8, 0xa2, 0xa9, 0x06, 0xfc, 0x0e, 0x35, 0xb6, 0x54,
	0xd2, 0x54, 0x79, 0x6e, 0xdf, 0x1d, 0x35, 0x27, 0x3d, 0x52, 0x91, 0x8b, 0x2c, 0x0c, 0x36, 0xad,
	0x9f, 0xfe, 0xf5, 0x9c, 0xa5, 0x6d, 0xc2, 0x3f, 0x10, 0x66, 0x82, 0x6b, 0x49, 0x99, 0x56, 0x61,
	0x0a, 0x9a, 0xae, 0xa8, 0xa6, 0xde, 0xa3, 0x7e, 0x6d, 0xd4, 0x9c, 0xbc, 0xae, 0x54, 0xcd, 0x6c,
	0xcb, 0x27, 0xdb, 0x60, 0xa5, 0x9d, 0x52, 0x55, 0x1c, 0xe0, 0x05, 0x7a, 0x1a, 0xfd, 0x12, 0x6c,
	0x13, 0x5a, 0x85, 0x57, 0x33, 0xea, 0x61, 0xa5, 0x7a, 0x9a, 0xd1, 0xcb, 0xbc, 0x68, 0xb5, 0xad,
	0xe8, 0xa6, 0x86, 0xe7, 0x08, 0xe9, 0x43, 0xa9, 0xab, 0x1b, 0xdd, 0xa0, 0x52, 0xf7, 0xf5, 0xf0,
	0xd0, 0xf5, 0x44, 0x17, 0x05, 0xfc, 0x19, 0x75, 0xd2, 0x84, 0x87, 0x4c, 0x70, 0x05, 0x5c, 0xed,
	0x54, 0xf8, 0x13, 0xc0, 0x7b, 0x6c, 0x2e, 0xf1, 0x25, 0xc9, 0x5f, 0x8b, 0x64, 0xaf, 0x55, 0xba,
	0xde, 0x03, 0x9b, 0x89, 0x84, 0x5b, 0x53, 0x3b, 0x4d, 0xf8, 0xac, 0xe8, 0xfd, 0x00, 0x80, 0xbf,
	0xa1, 0xb6, 0x9d, 0x1e, 0x4a, 0x60, 0x22, 0x4b, 0xd7, 0x30, 0xe9, 0x5e, 0x55, 0xa6, 0xb3, 0x51,
	0x96, 0x06, 0xb7, 0xde, 0x67, 0xf2, 0xb6, 0xa8, 0xa6, 0x1f, 0x4f, 0x17, 0xdf, 0x3d, 0x5f, 0x7c,
	0xf7, 0xff, 0xc5, 0x77, 0xff, 0x5c, 0x7d, 0xe7, 0x7c, 0xf5, 0x9d, 0xbf, 0x57, 0xdf, 0xf9, 0x3e,
	0x89, 0x13, 0xbd, 0xde, 0x45, 0x84, 0x89, 0x34, 0xb0, 0x13, 0xde, 0x70, 0xd0, 0x7b, 0x21, 0x37,
	0xc5, 0x7f, 0x70, 0x28, 0xf7, 0x49, 0x1f, 0xb7, 0xa0, 0xa2, 0x86, 0x59, 0xa3, 0xb7, 0xf7, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0xc9, 0x25, 0x6c, 0xe5, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardsRecords) > 0 {
		for iNdEx := len(m.RewardsRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardsRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.MinConsensusFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.TxRewards) > 0 {
		for iNdEx := len(m.TxRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.BlockRewards) > 0 {
		for iNdEx := len(m.BlockRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BlockRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ContractsMetadata) > 0 {
		for iNdEx := len(m.ContractsMetadata) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractsMetadata[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ContractsMetadata) > 0 {
		for _, e := range m.ContractsMetadata {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BlockRewards) > 0 {
		for _, e := range m.BlockRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TxRewards) > 0 {
		for _, e := range m.TxRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.MinConsensusFee.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RewardsRecords) > 0 {
		for _, e := range m.RewardsRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractsMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractsMetadata = append(m.ContractsMetadata, ContractMetadata{})
			if err := m.ContractsMetadata[len(m.ContractsMetadata)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockRewards = append(m.BlockRewards, BlockRewards{})
			if err := m.BlockRewards[len(m.BlockRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxRewards = append(m.TxRewards, TxRewards{})
			if err := m.TxRewards[len(m.TxRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinConsensusFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinConsensusFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardsRecords = append(m.RewardsRecords, RewardsRecord{})
			if err := m.RewardsRecords[len(m.RewardsRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
