apiVersion: v1
data:
  mnemonic: bHlyaWNzIHVwb24gbGFwdG9wIGN1dGUgdmVzc2VsIGNvdmVyIHNtaWxlIGFkZHJlc3Mgc3BlbGwgYmVnaW4gYXJtIHdlYXBvbiBtYWluIHN0YXJ0IGdyYWluIGxhcHRvcCBzdXN0YWluIGJhY2hlbG9yIGZvb3Qgam9iIG1vYmlsZSBtZW51IGNoaWNrZW4gaW5xdWlyeQ==
immutable: true
kind: Secret
metadata:
  name: titus-1-account
  namespace: testnets
---
apiVersion: v1
data:
  mnemonic: cXVpdCBlcnVwdCBjb29sIGludm9sdmUgcGhyYXNlIGN1cGJvYXJkIGZhY3VsdHkgZHJhZnQgc2xvZ2FuIGhhemFyZCBmdXJ5IHRhY2tsZSBzaGlwIHNpZWdlIHBhbmljIHJpdHVhbCBiZWxpZXZlIG1lbG9keSBkZW55IHB1bHAgbG91ZCBqZWFucyBhcGFydCByYW5kb20=
immutable: true
kind: Secret
metadata:
  name: titus-1-faucet-account
  namespace: testnets
---
apiVersion: v1
data:
  priv_validator_key.json: ewogICJhZGRyZXNzIjogIjM5MUE2MkRGQUFDNzdDRjlFMTZFNzYwM0FDMTVCQTM4MkI2M0Q2QjUiLAogICJwdWJfa2V5IjogewogICAgInR5cGUiOiAidGVuZGVybWludC9QdWJLZXlFZDI1NTE5IiwKICAgICJ2YWx1ZSI6ICJ4SFlwVGxwanZtcXVoVXZtV0VXeE9iQnJnRjNiVmF4S1VhWTR6WVVwL2FFPSIKICB9LAogICJwcml2X2tleSI6IHsKICAgICJ0eXBlIjogInRlbmRlcm1pbnQvUHJpdktleUVkMjU1MTkiLAogICAgInZhbHVlIjogInpYWllBbWZpeUF5ZmoxSEFBV1ZNeVFKQWcrOWpoNXdWanM1ZVN0UFVyY1BFZGlsT1dtTythcTZGUytaWVJiRTVzR3VBWGR0VnJFcFJwampOaFNuOW9RPT0iCiAgfQp9
immutable: true
kind: Secret
metadata:
  name: titus-1-private-key
  namespace: testnets
---
apiVersion: v1
data:
  genesis.json: |-
    {
      "genesis_time": "2022-10-07T20:54:05.216699013Z",
      "chain_id": "titus-1",
      "initial_height": "1",
      "consensus_params": {
        "block": {
          "max_bytes": "22020096",
          "max_gas": "100000000",
          "time_iota_ms": "1000"
        },
        "evidence": {
          "max_age_num_blocks": "100000",
          "max_age_duration": "172800000000000",
          "max_bytes": "1048576"
        },
        "validator": {
          "pub_key_types": [
            "ed25519"
          ]
        },
        "version": {}
      },
      "app_hash": "",
      "app_state": {
        "auth": {
          "params": {
            "max_memo_characters": "256",
            "tx_sig_limit": "7",
            "tx_size_cost_per_byte": "10",
            "sig_verify_cost_ed25519": "590",
            "sig_verify_cost_secp256k1": "1000"
          },
          "accounts": [
            {
              "@type": "/cosmos.auth.v1beta1.BaseAccount",
              "address": "archway1tfwqeexpqmr6pzpkfjzjaeyxtclzqu6ldz0r0r",
              "pub_key": null,
              "account_number": "0",
              "sequence": "0"
            },
            {
              "@type": "/cosmos.auth.v1beta1.BaseAccount",
              "address": "archway1pmwjjr9p4kzt80040y7cz3xxh2lvyh57t7velq",
              "pub_key": null,
              "account_number": "0",
              "sequence": "0"
            }
          ]
        },
        "authz": {
          "authorization": []
        },
        "bank": {
          "params": {
            "send_enabled": [],
            "default_send_enabled": true
          },
          "balances": [
            {
              "address": "archway1pmwjjr9p4kzt80040y7cz3xxh2lvyh57t7velq",
              "coins": [
                {
                  "denom": "utitus",
                  "amount": "100000000000000000"
                }
              ]
            },
            {
              "address": "archway1tfwqeexpqmr6pzpkfjzjaeyxtclzqu6ldz0r0r",
              "coins": [
                {
                  "denom": "utitus",
                  "amount": "10000000000000000000"
                }
              ]
            }
          ],
          "supply": [
            {
              "denom": "utitus",
              "amount": "10100000000000000000"
            }
          ],
          "denom_metadata": []
        },
        "capability": {
          "index": "1",
          "owners": []
        },
        "crisis": {
          "constant_fee": {
            "denom": "utitus",
            "amount": "1000"
          }
        },
        "distribution": {
          "params": {
            "community_tax": "0.020000000000000000",
            "base_proposer_reward": "0.010000000000000000",
            "bonus_proposer_reward": "0.040000000000000000",
            "withdraw_addr_enabled": true
          },
          "fee_pool": {
            "community_pool": []
          },
          "delegator_withdraw_infos": [],
          "previous_proposer": "",
          "outstanding_rewards": [],
          "validator_accumulated_commissions": [],
          "validator_historical_rewards": [],
          "validator_current_rewards": [],
          "delegator_starting_infos": [],
          "validator_slash_events": []
        },
        "evidence": {
          "evidence": []
        },
        "feegrant": {
          "allowances": []
        },
        "genutil": {
          "gen_txs": [
            {
              "body": {
                "messages": [
                  {
                    "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
                    "description": {
                      "moniker": "archway",
                      "identity": "",
                      "website": "",
                      "security_contact": "",
                      "details": ""
                    },
                    "commission": {
                      "rate": "0.100000000000000000",
                      "max_rate": "0.200000000000000000",
                      "max_change_rate": "0.010000000000000000"
                    },
                    "min_self_delegation": "1",
                    "delegator_address": "archway1tfwqeexpqmr6pzpkfjzjaeyxtclzqu6ldz0r0r",
                    "validator_address": "archwayvaloper1tfwqeexpqmr6pzpkfjzjaeyxtclzqu6ldxxpz2",
                    "pubkey": {
                      "@type": "/cosmos.crypto.ed25519.PubKey",
                      "key": "xHYpTlpjvmquhUvmWEWxObBrgF3bVaxKUaY4zYUp/aE="
                    },
                    "value": {
                      "denom": "utitus",
                      "amount": "1000000"
                    }
                  }
                ],
                "memo": "a29787a6ea3ec9f7f12870b18cffbf51cb91d1f9@10.48.1.128:26656",
                "timeout_height": "0",
                "extension_options": [],
                "non_critical_extension_options": []
              },
              "auth_info": {
                "signer_infos": [
                  {
                    "public_key": {
                      "@type": "/cosmos.crypto.secp256k1.PubKey",
                      "key": "A0FOA1ewwIOm/J5wAU+9z36E5YFzhH3yHH69eYOZ9Ck+"
                    },
                    "mode_info": {
                      "single": {
                        "mode": "SIGN_MODE_DIRECT"
                      }
                    },
                    "sequence": "0"
                  }
                ],
                "fee": {
                  "amount": [],
                  "gas_limit": "200000",
                  "payer": "",
                  "granter": ""
                }
              },
              "signatures": [
                "7zPXatblve5AqRb1ECUWlA+VTg77yKadM8R2mt7MVAVQfHXeVStLOrWiXGloPVYYQuwSL1SNclzPPlnkx8RE5Q=="
              ]
            }
          ]
        },
        "gov": {
          "starting_proposal_id": "1",
          "deposits": [],
          "votes": [],
          "proposals": [],
          "deposit_params": {
            "min_deposit": [
              {
                "denom": "utitus",
                "amount": "10000000"
              }
            ],
            "max_deposit_period": "172800s"
          },
          "voting_params": {
            "voting_period": "60s"
          },
          "tally_params": {
            "quorum": "0.334000000000000000",
            "threshold": "0.500000000000000000",
            "veto_threshold": "0.334000000000000000"
          }
        },
        "ibc": {
          "client_genesis": {
            "clients": [],
            "clients_consensus": [],
            "clients_metadata": [],
            "params": {
              "allowed_clients": [
                "06-solomachine",
                "07-tendermint"
              ]
            },
            "create_localhost": false,
            "next_client_sequence": "0"
          },
          "connection_genesis": {
            "connections": [],
            "client_connection_paths": [],
            "next_connection_sequence": "0",
            "params": {
              "max_expected_time_per_block": "30000000000"
            }
          },
          "channel_genesis": {
            "channels": [],
            "acknowledgements": [],
            "commitments": [],
            "receipts": [],
            "send_sequences": [],
            "recv_sequences": [],
            "ack_sequences": [],
            "next_channel_sequence": "0"
          }
        },
        "mint": {
          "minter": {
            "inflation": "0.130000000000000000",
            "annual_provisions": "0.000000000000000000"
          },
          "params": {
            "mint_denom": "utitus",
            "inflation_rate_change": "0.130000000000000000",
            "inflation_max": "0.200000000000000000",
            "inflation_min": "0.100000000000000000",
            "goal_bonded": "0.670000000000000000",
            "blocks_per_year": "31557600"
          }
        },
        "params": null,
        "rewards": {
          "params": {
            "inflation_rewards_ratio": "0.200000000000000000",
            "tx_fee_rebate_ratio": "0.500000000000000000",
            "max_withdraw_records": "25000"
          },
          "contracts_metadata": [],
          "block_rewards": [],
          "tx_rewards": [],
          "min_consensus_fee": {
            "denom": "utitus",
            "amount": "0"
          },
          "rewards_record_last_id": "0",
          "rewards_records": []
        },
        "slashing": {
          "params": {
            "signed_blocks_window": "100",
            "min_signed_per_window": "0.500000000000000000",
            "downtime_jail_duration": "600s",
            "slash_fraction_double_sign": "0.050000000000000000",
            "slash_fraction_downtime": "0.010000000000000000"
          },
          "signing_infos": [],
          "missed_blocks": []
        },
        "staking": {
          "params": {
            "unbonding_time": "1814400s",
            "max_validators": 100,
            "max_entries": 7,
            "historical_entries": 10000,
            "bond_denom": "utitus"
          },
          "last_total_power": "0",
          "last_validator_powers": [],
          "validators": [],
          "delegations": [],
          "unbonding_delegations": [],
          "redelegations": [],
          "exported": false
        },
        "tracking": {
          "tx_info_last_id": "0",
          "tx_infos": [],
          "contract_op_info_last_id": "0",
          "contract_op_infos": []
        },
        "transfer": {
          "port_id": "transfer",
          "denom_traces": [],
          "params": {
            "send_enabled": true,
            "receive_enabled": true
          }
        },
        "upgrade": {},
        "vesting": {},
        "wasm": {
          "params": {
            "code_upload_access": {
              "permission": "Everybody",
              "address": ""
            },
            "instantiate_default_permission": "Everybody"
          },
          "codes": [],
          "contracts": [],
          "sequences": [],
          "gen_msgs": []
        }
      }
    }
immutable: false
kind: ConfigMap
metadata:
  name: titus-1-genesis
  namespace: testnets
---
apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: titus-1
  namespace: testnets
spec:
  binaryName: archwayd
  config:
    resetDataOnGenesisChanges: true
    nodes:
      configOverride:
        app:
        - group: api
          key: enabled-unsafe-cors
          value:
            bool: true
        - group: telemetry
          key: enabled
          value:
            bool: true
        - group: telemetry
          key: enable-service-label
          value:
            bool: true
        - group: telemetry
          key: prometheus-retention-time
          value:
            int: 30
        - group: telemetry
          key: service-name
          value:
            string: archway
        - group: telemetry
          key: global-label
          value:
            stringListList:
            - - chain_id
              - titus-1
        config:
        - group: rpc
          key: cors_allowed_origins
          value:
            stringList:
            - '*'
        - group: instrumentation
          key: prometheus
          value:
            bool: true
    resetDataOnImageUpgrade: true
  expose:
    api: true
    domain: titus-1.archway.tech
    grpc: true
    p2p: true
    rpc: true
  image:
    name: docker.io/archwaynetwork/archwayd
    version: sha-f1307e2
    imagePullPolicy: Always
  init:
    assets:
    - 10000000000000000000utitus
    bondDenom: utitus
    chainID: titus-1
    faucet:
      creditAmount: 10000000
      denoms:
      - utitus
      domain: faucet.titus-1.archway.tech
      funds: 100000000000000000utitus
      legacySend: false
      maxCredit: 100000000
      replicas: 1
  moniker: archway
  persistence:
    autoResize:
      enabled: false
      increment: 5G
      threshold: 80
    size: 160G
  replicas: 4
  resources:
    sentry: {}
    validator: {}
  serviceMonitorLabels:
    release: monitoring-stack
