apiVersion: v1
data:
  settings.json: |-
    {
      "public":{
        "chainName":"Torii",
        "chainId":"torii-1",
        "gtm":"{Add your Google Tag Manager ID here}",
        "slashingWindow":10000,
        "uptimeWindow":250,
        "initialPageSize":30,
        "secp256k1":false,
        "bech32PrefixAccAddr":"archway",
        "bech32PrefixAccPub":"archwayopub",
        "bech32PrefixValAddr":"archwayvaloper",
        "bech32PrefixValPub":"archwayvaloperpub",
        "bech32PrefixConsAddr":"archwayvalcons",
        "bech32PrefixConsPub":"archwayvalconspub",
        "bondDenom":"utorii",
        "powerReduction":1000000,
        "coins":[
          {
            "denom":"utorii",
            "displayName":"Torii",
            "fraction":1000000
          }
        ],
        "ledger":{
          "coinType":118,
          "appName":"Cosmos",
          "appVersion":"2.16.0",
          "gasPrice":0.02
        },
        "modules":{
          "bank":true,
          "supply":true,
          "minting":false,
          "gov":true,
          "distribution":false
        },
        "coingeckoId":"cosmos",
        "networks":"https://gist.githubusercontent.com/kwunyeung/8be4598c77c61e497dfc7220a678b3ee/raw/bd-networks.json",
        "banners":false
      },
      "remote":{
        "rpc":"https://rpc.torii-1.archway.tech:443",
        "api":"https://api.torii-1.archway.tech:443"
      },
      "debug":{
        "startTimer":true
      },
      "params":{
        "startHeight":0,
        "defaultBlockTime":5000,
        "validatorUpdateWindow":300,
        "blockInterval":15000,
        "transactionsInterval":18000,
        "keybaseFetchingInterval":18000000,
        "consensusInterval":1000,
        "statusInterval":7500,
        "signingInfoInterval":1800000,
        "proposalInterval":5000,
        "recipeInterval":5000,
        "nftInterval":5000,
        "cookbookInterval":5000,
        "missedBlocksInterval":60000,
        "delegationInterval":900000
      }
    }
kind: ConfigMap
metadata:
  name: torii-1-bigdipper
  namespace: explorers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: torii-1-bigdipper
  name: torii-1-bigdipper
  namespace: explorers
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: torii-1-bigdipper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: torii-1-bigdipper
    spec:
      containers:
      - env:
        - name: ROOT_URL
          value: https://explorer.torii-1.archway.tech
        - name: MONGO_URL
          value: mongodb://mongodb:27017/meteor-torii
        - name: PORT
          value: "3000"
        - name: METEOR_SETTINGS
          valueFrom:
            configMapKeyRef:
              key: settings.json
              name: torii-1-bigdipper
        image: drewstaylor/bigdipper:1.0.0-archway
        imagePullPolicy: Always
        name: torii-1-bigdipper
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: torii-1-bigdipper
  namespace: explorers
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: torii-1-bigdipper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/name: torii-1-bigdipper
  name: torii-1-bigdipper
  namespace: explorers
spec:
  rules:
    - host: explorer.torii-1.archway.tech
      http:
        paths:
          - backend:
              service:
                name: torii-1-bigdipper
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - explorer.torii-1.archway.tech
      secretName: torii-1-bigdipper-cert

