# DEPRECATED
name: Build deprecated docker image

on:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    outputs:
      image-version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: archwaynetwork/archwayd
          tags: |
            type=semver,pattern={{raw}}
            type=sha


      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.deprecated
