name: Linter

# Run on every master merge and on PRs.
on:
  push:
    branches: [main]
    tags: [v*]

  pull_request:
    branches: [main]

  workflow_dispatch:
    branches: [main]
    
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --fix=false
          only-new-issues: true