name: Publish to Buf Schema Registry
# Protobuf runs buf (https://buf.build/) push updated proto files to https://buf.build/cosmos/cosmos-sdk
# This workflow is only run when a .proto file has been changed
on:
  push:
    branches: [main]
    tags: [v*]
    paths:
      - proto/**
  pull_request:
    paths:
      - proto/**
      - .github/workflows/proto-registry.yaml

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.32.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
      - uses: bufbuild/buf-push-action@v1
        with:
          input: proto
          draft: ${{ github.ref_name != 'main'}}
          buf_token: ${{ secrets.BUF_TOKEN }}
